"""Join the five per-architecture sweep kernels into one table.

The sweep runs as five Kaggle kernels rather than one -- DCRNN alone measures
~10 h against Kaggle's 12 h CPU limit -- so the cross-architecture table has to be
assembled after the fact. Each kernel writes ``improved_sweep_<ARCH>.json`` with
an identical record schema, and this script concatenates them, checks the
persistence floor agrees across all five, and prints the tables.

Usage::

    kaggle kernels output <user>/improved-architecture-sweep-stgat -p analysis/results/sweep
    ...                                                                   (x5)
    python analysis/_build/merge_sweep.py

Writes ``analysis/results/improved_sweep.md`` and ``improved_sweep.json``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent.parent
IN_DIR = REPO / "analysis" / "results" / "sweep"
OUT_JSON = REPO / "analysis" / "results" / "improved_sweep.json"
OUT_MD = REPO / "analysis" / "results" / "improved_sweep.md"

ARCH_ORDER = ["STGAT", "A3TGCN", "ASTGCN", "DCRNN", "AAGCN"]
INC_ORDER = ["base", "per_horizon_heads", "temporal_attention", "huber", "probabilistic"]

#: The two ways every fold is scored. See ``analysis/lib/improved.py``.
FIELDS = [
    ("RMSE", "all windows"),
    ("RMSE_clean", "artifact-free"),
]


def load(in_dir: Path) -> list[dict]:
    """Concatenate the per-architecture JSONs, keeping one copy of the floor.

    Every kernel recomputes persistence on the same folds, so five identical
    copies arrive. They are collapsed to one -- and disagreement between them is
    raised rather than averaged away, because it would mean the kernels ran
    against different data or a different protocol.
    """
    files = sorted(in_dir.glob("improved_sweep_*.json"))
    if not files:
        raise SystemExit(f"no improved_sweep_*.json under {in_dir}")

    records: list[dict] = []
    floors: dict[tuple, dict] = {}
    for path in files:
        for r in json.loads(path.read_text(encoding="utf-8")):
            if r["arch"] != "persistence":
                records.append(r)
                continue
            seen = floors.setdefault(r["origin"], r)
            for field, _ in FIELDS:
                if abs(seen[field] - r[field]) > 1e-6:
                    raise SystemExit(
                        f"persistence floor disagrees at origin {r['origin']}: "
                        f"{seen[field]} vs {r[field]} in {path.name} -- the kernels "
                        f"did not run the same protocol or the same data"
                    )
    print(f"{len(files)} kernel output(s): "
          f"{', '.join(sorted({r['arch'] for r in records}))}")
    return list(floors.values()) + records


def grid(records: list[dict], field: str) -> tuple[list[str], list[str], dict]:
    archs = [a for a in ARCH_ORDER if any(r["arch"] == a for r in records)]
    present = {r["increment"] for r in records if r["arch"] != "persistence"}
    incs = [i for i in INC_ORDER if i in present] + sorted(present - set(INC_ORDER))
    cells = {}
    for a in archs:
        for i in incs:
            v = [r[field] for r in records if r["arch"] == a and r["increment"] == i]
            cells[a, i] = (float(np.mean(v)), len(v)) if v else (float("nan"), 0)
    return archs, incs, cells


def paired(records: list[dict], field: str) -> list[tuple]:
    """Increment minus base on matched (architecture, origin, seed) runs.

    Pairing is the whole point: the three origins differ in difficulty by more
    than any increment moves the number, so an unpaired standard deviation is
    fold difficulty wearing a model's name.
    """
    from scipy import stats

    def key(r):
        return (r["arch"], r["origin"], r["seed"])

    basis = {key(r): r[field] for r in records if r["increment"] == "base"}
    rows = []
    for i in INC_ORDER[1:]:
        pairs = [(r[field], basis[key(r)]) for r in records
                 if r["increment"] == i and key(r) in basis]
        if len(pairs) < 3:
            continue
        d = np.array([a - b for a, b in pairs])
        _, p = stats.ttest_rel([a for a, _ in pairs], [b for _, b in pairs])
        rows.append((i, float(d.mean()), float(d.std(ddof=1)),
                     int((d < 0).sum()), len(d), float(p)))
    return rows


def render(records: list[dict]) -> str:
    out: list[str] = []
    w = out.append
    w("# Improved-architecture sweep\n")
    w("Five verified architectures under `docs/ROADMAP.md`'s frozen protocol, ")
    w("each with four evidence-led increments. Generated by ")
    w("`analysis/_build/merge_sweep.py` from the five Kaggle kernels.\n")
    w("\nEvery fold is scored twice. `all windows` is what the frozen protocol ")
    w("reports; `artifact-free` drops the six origin-0.85 test windows touching ")
    w("the week-395 reporting spike, from every arm and from the floor alike. ")
    w("Roughly 90% of that fold's squared error comes from those six windows, and ")
    w("the fold ordering inverts between the two tables -- so no statement about ")
    w("'the hard fold' means anything without saying which table it came from.\n")

    for field, caption in FIELDS:
        floor = float(np.mean([r[field] for r in records if r["arch"] == "persistence"]))
        archs, incs, cells = grid(records, field)
        w(f"\n## Pooled RMSE, {caption}\n\n")
        w(f"Persistence floor: **{floor:.2f}**\n\n")
        w("| architecture | " + " | ".join(f"`{i}`" for i in incs) + " |\n")
        w("|---" * (len(incs) + 1) + "|\n")
        for a in archs:
            row = []
            for i in incs:
                mean, n = cells[a, i]
                row.append("--" if n == 0 else f"{mean:.2f}")
            w(f"| {a} | " + " | ".join(row) + " |\n")

        w(f"\n### Paired against `base`, {caption}\n\n")
        w("| increment | mean ΔRMSE | sd | better | p |\n|---|---|---|---|---|\n")
        for name, mean, sd, better, n, p in paired(records, field):
            w(f"| `{name}` | {mean:+.3f} | {sd:.3f} | {better}/{n} | {p:.3f} |\n")

    prob = [r for r in records if r["increment"] == "probabilistic" and "PICP" in r]
    if prob:
        w("\n## Eq. (14) intervals, nominal coverage 0.95\n\n")
        w("| architecture | PICP | MPIW |\n|---|---|---|\n")
        for a in [x for x in ARCH_ORDER if any(r["arch"] == x for r in prob)]:
            rows = [r for r in prob if r["arch"] == a]
            w(f"| {a} | {np.mean([r['PICP'] for r in rows]):.3f} | "
              f"{np.mean([r['MPIW'] for r in rows]):.1f} |\n")

    counts = sorted({(r["arch"], r["increment"]) for r in records if r["arch"] != "persistence"})
    expected = len(ARCH_ORDER) * len(INC_ORDER)
    w(f"\n{len(counts)}/{expected} (architecture, increment) cells present.\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in-dir", type=Path, default=IN_DIR)
    args = ap.parse_args()

    # The table uses a real delta sign, and Windows consoles default to cp1252.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    records = load(args.in_dir)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(records, indent=1), encoding="utf-8")
    markdown = render(records)
    OUT_MD.write_text(markdown, encoding="utf-8")
    print(markdown)
    print(f"-> {OUT_JSON}\n-> {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
