"""Write the ICITR (IEEE, 6-page) paper's tables, one file each, into full_paper/icitr/tables/.

The tables are the ones the long ACM draft uses, built by the same functions from the same
run outputs, so the two versions cannot disagree:

* ``scripts/build_paper_assets.py``       encoders, rescue (Kaggle run, EXP-050)
* ``scripts/build_paper_extra_tables.py`` compute, prospective (Kaggle run; EXP-063)

Only the font size changes, because IEEE columns are narrower than ACM's.

    python scripts/build_icitr_tables.py
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "full_paper" / "icitr" / "tables"


def load(name: str):
    spec = importlib.util.spec_from_file_location(name, REPO / "scripts" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def write(name: str, tex: str, source: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text(
        f"% Generated by scripts/build_icitr_tables.py from {source} (tab:{name}) -- do not edit by hand.\n\n"
        + tex.replace(r"\small", r"\footnotesize")
        + "\n",
        encoding="utf-8",
    )


def main() -> None:
    assets = load("build_paper_assets")
    extra = load("build_paper_extra_tables")
    r3, _, _, res, _ = assets.load()
    for name, build, args in (("encoders", assets.table_encoders, (r3,)),
                              ("rescue", assets.table_rescue, (r3, res))):
        out: list[str] = []
        build(*args, out)
        write(name, "\n".join(out), "build_paper_assets.py")
    write("compute", extra.compute_table(extra.model_namespace()), "build_paper_extra_tables.py")
    write("prospective", extra.prospective_table(), "build_paper_extra_tables.py")
    print(f"tables written to {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
