"""Architecture comparison table: published designs on our shared pipeline.

Answers one question -- does replacing our spatial or temporal operator with the
one a published architecture uses beat the operator it replaces, and does any of
them beat persistence?

Two reference columns, because they answer different things:

  vs persistence   the absolute bar. Under this protocol persistence is strong,
                   and an architecture that loses to it is not forecasting.
  vs X_gcn         the attributable bar. X_gcn shares every other component, so
                   a difference here is the architecture (D7). This is the
                   column that says whether attention or recurrence earned its
                   parameters.

Both are paired sign tests over matched (fold, seed), reusing make_tables so the
statistics are computed one way in this repository, not two.

Usage:
    python scripts/compare_arch.py [--results results/phase3_arch.csv]
"""

from __future__ import annotations

import argparse
import statistics as st
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

from make_tables import load, mean_sd, pooled, sign_test  # noqa: E402

#: Display names and what each arm is a rendering of.
ARMS = {
    "X_gcn": ("GCN (control)", "adaptive GCN, no temporal operator"),
    "X_gcn_gtcn": ("GCN + gated TCN", "Graph WaveNet temporal block"),
    "X_gat": ("GAT", "Velickovic attention, no temporal operator"),
    "X_stgat": ("STGAT", "GAT + LSTM"),
    "X_a3tgcn": ("A3TGCN", "GCN + GRU with attention over timesteps"),
    "X_gat_h1": ("GAT 1-head", "7,160 params: matched to the GCN control's 7,032"),
    "X_gat_h2": ("GAT 2-head", "13,624 params: matched to GCN hidden=96"),
    "X_gcn_h96": ("GCN h96", "13,368 params: capacity control for GAT 2-head"),
    "X_gcn_h128": ("GCN h128", "21,752 params: capacity control for A3TGCN's 23,865"),
}
CONTROL = "X_gcn"
BASE = "persistence"


def stat_line(rows: list[dict], label: str) -> dict:
    vals = [float(r["rmse"]) for r in rows if r["label"] == label]
    if not vals:
        return {}
    mean, sd = mean_sd(vals)
    meta = next((r for r in rows if r["label"] == label), {})

    def num(field: str, cast=float):
        v = meta.get(field, "")
        return cast(v) if v not in ("", "nan", None) else None

    w_p, n_p, p_p = sign_test(rows, label, BASE)
    out = {
        "label": label,
        "n": len(vals),
        "mean": mean,
        "sd": sd,
        "median": st.median(vals),
        "params": num("n_params", int),
        "train_s": num("train_seconds"),
        "vs_base": (w_p, n_p, p_p),
    }
    if label != CONTROL:
        out["vs_ctrl"] = sign_test(rows, label, CONTROL)
    return out


def fmt_test(t: tuple[int, int, float] | None) -> str:
    if not t or t[1] == 0:
        return "-"
    w, n, p = t
    return f"{w}/{n} p={p:.3f}"


def render(stats: list[dict], base_mean: float | None) -> str:
    out = [
        "# Architecture comparison",
        "",
        "Generated by `scripts/compare_arch.py`. Pooled RMSE, mean over (fold, seed).",
        "Lower is better. Sign-test columns give wins/comparisons and a two-sided p.",
        "",
        "| architecture | RMSE mean +/- SD | median | params | train s | vs persistence | vs GCN control |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    if base_mean is not None:
        out.append(f"| persistence | {base_mean:.2f} | - | - | - | - | - |")
    for s in stats:
        disp = ARMS.get(s["label"], (s["label"], ""))[0]
        out.append(
            f"| {disp} | {s['mean']:.2f} +/- {s['sd']:.2f} | {s['median']:.2f} | "
            f"{s['params'] or '-'} | {s['train_s']:.1f} | "
            f"{fmt_test(s['vs_base'])} | {fmt_test(s.get('vs_ctrl'))} |"
        )
    out += [
        "",
        "The `vs GCN control` column is only attributable where capacity is matched.",
        "At hidden=64 it is not: GAT carries 7.5x the control's parameters and STGAT",
        "12.5x, so those two rows conflate architecture with width. The matched",
        "pairs -- GAT 1-head vs GCN, GAT 2-head vs GCN h96, A3TGCN vs GCN h128 --",
        "are the comparisons that isolate the architecture.",
        "",
        "## What each arm is",
        "",
    ]
    for lab, (disp, what) in ARMS.items():
        if any(s["label"] == lab for s in stats):
            out.append(f"- **{disp}** (`{lab}`): {what}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--results",
        type=Path,
        nargs="+",
        default=[
            REPO / "results" / "phase3_arch.csv",
            REPO / "results" / "phase3_arch_cap.csv",
        ],
        help="Result files to merge. The capacity-matched arms were run as a "
        "separate batch under the same protocol, so they merge cleanly.",
    )
    ap.add_argument("--out", type=Path, default=REPO / "results" / "table_arch.md")
    args = ap.parse_args()

    rows = pooled(load(list(args.results)))
    present = [k for k in ARMS if any(r["label"] == k for r in rows)]
    stats = [s for k in present if (s := stat_line(rows, k))]
    stats.sort(key=lambda s: s["mean"])

    base = [float(r["rmse"]) for r in rows if r["label"] == BASE]
    base_mean = st.mean(base) if base else None

    args.out.write_text(render(stats, base_mean), encoding="utf-8")
    print(args.out.read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
