"""Measure how far each architecture's prediction actually moves from persistence.

Motivated by a result that reads as a win and is not one. In the architecture
study STGAT has the lowest mean RMSE *and* a paired-difference SD against
persistence of 0.70, where every other arm sits at 9.5-17.0. An architecture
that beats persistence by tracking it to within +/-0.7 RMSE on every fold is not
outperforming it; it is reproducing it.

Under the residual parameterisation (ADR-0001) the model predicts a correction
that is added back to persistence, so a model whose output collapses to zero
*is* persistence, and inherits its score exactly. That is the safest possible
model under this loss and it wins on mean RMSE without forecasting anything.

This script measures the collapse directly:

    move   = mean |prediction - persistence|      what the model actually adds
    needed = mean |truth      - persistence|      what it would have to add
    ratio  = move / needed

A ratio near 0 is a collapsed model. Near 1 means corrections on the scale the
data demands -- which says nothing about whether they point the right way, only
that the model is making them. Report it beside RMSE, never instead of it.

Usage:
    python scripts/diagnose_residual.py [--folds 0 4 7] [--seed 0]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO / "scripts"))

from run_phase3 import ADJ, NPY, arch_configs  # noqa: E402

from dengue_gnn.experiment import (  # noqa: E402
    _evaluate,
    _persistence_counts,
    fold_split,
    load_dataset,
)


def collapse_ratio(raw, adj, cfg, fold_idx: int, seed: int) -> dict:
    """Train one (fold, seed) and compare its correction against the needed one."""
    import torch

    from dengue_gnn.experiment import FoldData, _build_fold, select_shrinkage, train_fold

    torch.set_num_threads(1)
    # Mirrors run_single's fold construction exactly. Anything else here would
    # measure a different fold than the results CSV reports.
    train_ids, val_ids, test_ids, _origin = fold_split(raw, cfg, fold_idx)
    (xtr, ytr, ptr), (xva, yva, pva), tmean, tstd = _build_fold(raw, cfg, train_ids, val_ids)
    _, (xte, yte, pte), _, _ = _build_fold(raw, cfg, train_ids, test_ids)
    fold = FoldData(xtr, ytr, ptr, xva, yva, pva, xte, yte, pte, tmean, tstd, test_ids)
    torch.manual_seed(seed)
    np.random.seed(seed)  # noqa: NPY002

    model = train_fold(fold, cfg, adj, None)
    gamma = select_shrinkage(model, fold, cfg, None)
    pred, truth = _evaluate(model, xte, yte, pte, fold, cfg, None, gamma)
    persist, _ = _persistence_counts(raw, cfg, test_ids)

    move = float(np.mean(np.abs(pred - persist)))
    needed = float(np.mean(np.abs(truth - persist)))
    return {
        "label": cfg.label,
        "fold": fold_idx,
        "seed": seed,
        "move": move,
        "needed": needed,
        "ratio": move / needed if needed else float("nan"),
        "gamma": gamma,
        "rmse": float(np.sqrt(np.mean((pred - truth) ** 2))),
        "rmse_persist": float(np.sqrt(np.mean((persist - truth) ** 2))),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--folds", type=int, nargs="+", default=[0, 4, 7])
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", type=Path, default=REPO / "results" / "table_collapse.md")
    args = ap.parse_args()

    raw, adj = load_dataset(str(NPY), str(ADJ))[:2]
    cfgs = {c.label: c for c in arch_configs(quick=False)}

    recs = []
    for label in ("X_gcn", "X_gcn_gtcn", "X_gat", "X_stgat", "X_a3tgcn"):
        for fold_idx in args.folds:
            rec = collapse_ratio(raw, adj, cfgs[label], fold_idx, args.seed)
            recs.append(rec)
            print(
                f"  {label:12s} fold{fold_idx}  move {rec['move']:7.2f}  "
                f"needed {rec['needed']:7.2f}  ratio {rec['ratio']:5.3f}  "
                f"RMSE {rec['rmse']:6.2f} (persist {rec['rmse_persist']:6.2f})",
                flush=True,
            )

    lines = [
        "# Residual-collapse diagnostic",
        "",
        "Generated by `scripts/diagnose_residual.py`.",
        "`move` is the mean absolute correction the model adds to persistence;",
        "`needed` is the correction that would be required to reach the truth.",
        "A `ratio` near 0 means the model has collapsed onto persistence and its",
        "RMSE is persistence's RMSE, not a forecast.",
        "",
        "| arm | fold | move | needed | ratio | RMSE | persistence RMSE |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in recs:
        lines.append(
            f"| {r['label']} | {r['fold']} | {r['move']:.2f} | {r['needed']:.2f} | "
            f"{r['ratio']:.3f} | {r['rmse']:.2f} | {r['rmse_persist']:.2f} |"
        )
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {args.out.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
