"""Index every results CSV against its manifest, into results/RUNS.md.

A manifest tells you about one run. This tells you about the collection: which
CSV came from which commit, whether that commit was enough to reproduce it, and
whether the run actually finished.

The completeness check is the point. A run that died at job 90 of 128 leaves a
CSV that looks perfectly well-formed -- correct header, plausible numbers, no
error anywhere in it -- and there is nothing in the file itself to say a third
of the arms are missing. Comparing the distinct ``(label, fold, seed)`` triples
present against the job count the manifest recorded catches that. Counting rows
would not, because rows per job depends on the horizon count.

Files with no manifest are listed too, and deliberately not hidden: every
pre-provenance CSV in this repository is one whose exact origin is already
unrecoverable, which is review finding F1 and the reason this module exists.

Usage:
    python scripts/index_runs.py [--out results/RUNS.md]
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "results"


def read_csv_summary(path: Path) -> dict[str, Any]:
    """Distinct arms, folds, seeds and jobs actually present in a results file."""
    try:
        with open(path, newline="", encoding="utf-8") as fh:
            rows = list(csv.DictReader(fh))
    except (OSError, csv.Error) as exc:
        return {"error": str(exc)}
    if not rows:
        return {"error": "empty"}

    def col(name: str) -> set[str]:
        return {r[name] for r in rows if r.get(name) not in (None, "")}

    jobs = {(r.get("label"), r.get("fold"), r.get("seed")) for r in rows}
    return {
        "n_rows": len(rows),
        "labels": sorted(col("label")),
        "n_folds": len(col("fold")),
        "n_seeds": len(col("seed")),
        "n_jobs_present": len(jobs),
    }


def load_manifest(csv_path: Path) -> dict[str, Any] | None:
    path = csv_path.with_suffix(csv_path.suffix + ".manifest.json")
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def describe(csv_path: Path) -> dict[str, Any]:
    summary = read_csv_summary(csv_path)
    man = load_manifest(csv_path)
    rec: dict[str, Any] = {"file": csv_path.name, **summary}

    if man is None:
        rec["provenance"] = "none"
        # Not a defect to fix by deleting the row -- the CSV is still the
        # evidence for whatever cited it. It is a claim to make cautiously.
        rec["status"] = "unattributable"
        return rec

    git = man.get("git", {})
    extra = man.get("extra", {})
    sha = (git.get("commit") or "")[:8] or "unknown"
    rec["provenance"] = f"{sha}{'+dirty' if git.get('dirty') else ''}"
    rec["mode"] = extra.get("mode", "")
    rec["note"] = extra.get("note", "")
    rec["wall_seconds"] = extra.get("wall_seconds")

    scheduled = man.get("n_jobs_scheduled")
    present = summary.get("n_jobs_present")
    if extra.get("status") == "started":
        # The post-run write never happened: the process died mid-flight.
        rec["status"] = "CRASHED"
    elif scheduled and present and present < scheduled:
        rec["status"] = f"TRUNCATED {present}/{scheduled}"
    elif scheduled and present and present > scheduled:
        # More arms than the run scheduled: the CSV was merged or appended to.
        rec["status"] = f"MERGED {present}/{scheduled}"
    elif summary.get("error"):
        rec["status"] = "unreadable"
    else:
        rec["status"] = "complete"
    if git.get("dirty"):
        # The SHA alone does not reproduce this; say so where it is read.
        rec["status"] += " (dirty tree)"
    return rec


def render(records: list[dict[str, Any]]) -> str:
    out = [
        "# Results index",
        "",
        "Generated by `scripts/index_runs.py`. Do not edit by hand.",
        "",
        "`provenance` is the commit a run was made from; `+dirty` means the working",
        "tree had uncommitted changes, so that SHA alone will not reproduce the",
        "numbers. `unattributable` means the CSV predates automatic provenance",
        "capture and its exact origin cannot be recovered (see PHASE2_REVIEW F1).",
        "",
        "| file | status | provenance | arms | folds | seeds | rows | note |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in records:
        labels = r.get("labels") or []
        arms = str(len(labels)) if labels else "-"
        out.append(
            "| `{file}` | {status} | {prov} | {arms} | {folds} | {seeds} | {rows} | {note} |".format(
                file=r["file"],
                status=r.get("status", "?"),
                prov=r.get("provenance", "?"),
                arms=arms,
                folds=r.get("n_folds", "-"),
                seeds=r.get("n_seeds", "-"),
                rows=r.get("n_rows", "-"),
                note=(r.get("note") or "").replace("|", "/"),
            )
        )

    out += ["", "## Arms per file", ""]
    for r in records:
        labels = r.get("labels")
        if labels:
            out.append(f"- `{r['file']}`: {', '.join(labels)}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", type=Path, default=RESULTS)
    ap.add_argument("--out", type=Path, default=RESULTS / "RUNS.md")
    args = ap.parse_args()

    files = sorted(p for p in args.results.glob("*.csv"))
    records = [describe(p) for p in files]
    args.out.write_text(render(records), encoding="utf-8")

    bad = [r for r in records if r.get("status", "").startswith(("CRASHED", "TRUNCATED"))]
    unattributed = [r for r in records if r.get("provenance") == "none"]
    print(f"indexed {len(records)} result files -> {args.out.name}")
    print(f"  {len(unattributed)} without provenance, {len(bad)} incomplete")
    for r in bad:
        print(f"  ! {r['file']}: {r['status']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
