"""Check our SEIR-SEI implementation against Phaijoo & Gurung (2018), and derive the growth ceiling.

Three jobs, in order.

1. **Reproduce the paper's Table 1.** Our nine sensitivity indices must match the
   published ones. This is the strongest available test that the transcription of
   F, V and R0 is right: the indices depend on the whole formula, so a wrong
   entry anywhere shows up here. Eight match exactly; ``mu_v`` differs by exactly
   0.5 for a documented reparameterisation reason (see ``seir.sensitivity_indices``).

2. **Report a discrepancy in the paper.** Table 1's "Baseline Values" column does
   not produce Table 1's own indices. Five of nine disagree. The published indices
   correspond instead to the section-4 simulation values. Anyone citing the
   baseline column gets different numbers, so we cite section 4 and say why.

3. **Derive the growth ceiling** that replaces the guessed
   ``MAX_WEEKLY_LOG_GROWTH = 0.70``, and check it against the growth rates
   actually observed in our data.

Usage:
    python scripts/verify_seir_paper.py [--out results/table_seir_validation.md]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from dengue_gnn.seir import (  # noqa: E402
    PAPER_SECTION4,
    Params,
    growth_rate,
    next_generation_matrices,
    r0,
    sensitivity_indices,
    weekly_log_growth_ceiling,
)

#: Table 1 of the paper, as published.
PAPER_INDICES = {
    "m": 0.5,  # published against pi_v, which enters R0 only through m
    "b": 1.0,
    "beta_v": 0.5,
    "mu_v": -1.31823,
    "nu_v": 0.318228,
    "beta_h": 0.5,
    "gamma_h": -0.49993,
    "mu_h": -0.000208,
    "nu_h": 0.000138,
}

#: The paper's Table 1 "Baseline Values" column, which disagrees with the
#: indices printed beside it. Kept to demonstrate that, not to use.
TABLE1_BASELINES = Params(
    b=0.5,
    beta_h=0.75,
    beta_v=1.0,
    m=5000.0 / (0.02941 * 5071126.0),
    mu_v=0.02941,
    nu_v=0.1428,
    nu_h=1.667,
    gamma_h=0.328833,
    mu_h=0.0045,
)

#: The reparameterisation offset explained in seir.sensitivity_indices.
MU_V_OFFSET = -0.5


def observed_growth(repo: Path) -> np.ndarray:
    """Absolute weekly log growth of reported cases, per district-week."""
    from dengue_gnn.data import load_cases

    cases = load_cases(repo / "notebooks" / "baseline" / "sri_lanka_2013-2022_shifted.npy")
    return np.abs(np.diff(np.log1p(np.clip(cases, 0, None)), axis=0))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=REPO / "results" / "table_seir_validation.md")
    ap.add_argument("--r0-max", type=float, default=6.0)
    args = ap.parse_args()

    out: list[str] = [
        "# SEIR-SEI validation against Phaijoo & Gurung (2018)",
        "",
        "Generated by `scripts/verify_seir_paper.py`.",
        "",
        "## 1. Sensitivity indices reproduce Table 1",
        "",
        "| parameter | ours | paper | agrees |",
        "| --- | --- | --- | --- |",
    ]

    ours = sensitivity_indices(PAPER_SECTION4)
    all_ok = True
    for k, published in PAPER_INDICES.items():
        expected = published + (MU_V_OFFSET if k == "mu_v" else 0.0)
        ok = abs(ours[k] - expected) < 2e-5
        all_ok &= ok
        note = "yes" if ok else "NO"
        if k == "mu_v" and ok:
            note = "yes, after the documented -0.5 reparameterisation offset"
        out.append(f"| `{k}` | {ours[k]:+.6f} | {published:+.6f} | {note} |")

    f, v = next_generation_matrices(PAPER_SECTION4)
    rho = float(max(abs(np.linalg.eigvals(f @ np.linalg.inv(v)))))
    closed = r0(PAPER_SECTION4)
    out += [
        "",
        f"Closed-form R0 = {closed:.6f}; spectral radius of `F V^-1` = {rho:.6f}. "
        f"Two independent routes to the same number.",
        "",
        f"At the paper's own section-4 values R0 = {closed:.4f} < 1, so the growth rate "
        f"is negative ({growth_rate(PAPER_SECTION4):+.5f}/day) and the disease-free "
        "equilibrium is stable -- consistent with the paper's Theorem 3.2.",
        "",
        "## 2. Table 1's baseline column disagrees with Table 1's indices",
        "",
        "| parameter | index at Table-1 baselines | index published in Table 1 | agrees |",
        "| --- | --- | --- | --- |",
    ]

    t1 = sensitivity_indices(TABLE1_BASELINES)
    n_bad = 0
    for k, published in PAPER_INDICES.items():
        expected = published + (MU_V_OFFSET if k == "mu_v" else 0.0)
        ok = abs(t1[k] - expected) < 2e-5
        n_bad += not ok
        out.append(f"| `{k}` | {t1[k]:+.6f} | {published:+.6f} | {'yes' if ok else 'NO'} |")

    out += [
        "",
        f"{n_bad} of {len(PAPER_INDICES)} disagree. The published indices reproduce at the "
        "section-4 simulation values, not at the baselines Table 1 prints. We cite "
        "section 4.",
        "",
        "## 3. The growth ceiling",
        "",
        "`ln(R0)/GI` assumes every onward infection lands exactly one generation "
        "interval later. The model's stage durations are exponential, and for a given "
        "R0 that produces faster early growth than a fixed delay -- so the naive "
        "formula understates the bound.",
        "",
        "| R0 cap | max lambda /day | max weekly log growth | naive ln(R0)/3wk | ratio |",
        "| --- | --- | --- | --- | --- |",
    ]

    for cap in (2.0, 3.0, 4.0, 6.0, 8.0, 10.0):
        ceiling, _ = weekly_log_growth_ceiling(cap)
        naive = float(np.log(cap) / 3.0)
        out.append(
            f"| {cap:g} | {ceiling / 7:.5f} | {ceiling:.4f} | {naive:.4f} | {ceiling / naive:.2f}x |"
        )

    ceiling, argmax = weekly_log_growth_ceiling(args.r0_max)
    obs = observed_growth(REPO)
    out += [
        "",
        f"At the chosen cap R0 <= {args.r0_max:g} the ceiling is **{ceiling:.4f}** per week, "
        f"attained at b={argmax.b:g}, beta_h={argmax.beta_h:g}, beta_v={argmax.beta_v:g}, "
        f"m={argmax.m:g}, 1/mu_v={1 / argmax.mu_v:.1f}d, 1/nu_v={1 / argmax.nu_v:.1f}d, "
        f"1/nu_h={1 / argmax.nu_h:.1f}d, 1/gamma_h={1 / argmax.gamma_h:.1f}d "
        f"(R0 = {r0(argmax):.2f}).",
        "",
        "### Against the observed data",
        "",
        f"{obs.size} district-week growth rates, {obs.shape[1]} districts:",
        "",
        "| threshold | observations above | share |",
        "| --- | --- | --- |",
    ]
    for thr, name in ((0.70, "old guessed ceiling 0.70"), (ceiling, f"derived {ceiling:.4f}")):
        n = int((obs > thr).sum())
        out.append(f"| {name} | {n} | {100 * n / obs.size:.2f}% |")

    out += [
        "",
        "The old ceiling declared a fifth of the recorded data physically impossible. "
        "A constraint that a fifth of the observations violate is not encoding physics; "
        "it is penalising forecasts for tracking real outbreak dynamics, which is the "
        "behaviour we most want. That is the likeliest explanation for the band term "
        "never helping in Stage 2b or Stage 3.",
    ]

    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))
    print(f"\nwrote {args.out.name}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
